export const theme = {
  scheme: 'default',
  base00: '#fff',
  base01: 'inherit',
  base02: 'inherit',
  base03: 'inherit',
  base04: 'inherit',
  base05: 'inherit',
  base06: 'inherit',
  base07: 'inherit',
  base08: 'inherit',
  base09: 'inherit',
  base0A: 'inherit',
  base0B: 'inherit',
  base0C: 'inherit',
  base0D: 'inherit',
  base0E: 'inherit',
  base0F: 'inherit',
};
